name: CUDA Build & Run

on: [push]

jobs:
  cuda:
    runs-on: ubuntu-latest

    container:
      image: nvidia/cuda:12.4.1-devel-ubuntu22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: apt-get update && apt-get install -y build-essential

      - name: Compile CUDA
        run: nvcc main.cu -o program

      - name: Run program
        run: ./program
